version: 2

models:
  - name: stg_orders
    description: Staging model for orders with timestamp parsing and ingestion lineage.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - load_date

    columns:
      - name: order_id
        description: Order identifier (unique within each load_date batch).
        tests:
          - not_null

      - name: customer_id
        description: Customer who placed the order.
        tests:
          - not_null

      - name: order_status
        description: Current status of the order.
        tests:
          - accepted_values:
              arguments:
                values:
                  - created
                  - approved
                  - invoiced
                  - processing
                  - shipped
                  - delivered
                  - canceled
                  - unavailable

      - name: order_purchase_ts
        description: Timestamp when the order was created.
        tests:
          - not_null

      - name: order_purchase_dt
        description: Order creation date derived from order_purchase_ts.
        tests:
          - not_null

      - name: load_date
        description: Batch partition date used for ingestion lineage and idempotency.
        tests:
          - not_null

      - name: ingestion_ts
        description: Ingestion timestamp for lineage and debugging.
        tests:
          - not_null

      - name: source_file
        description: Source file name used during ingestion (if available).

      - name: source_uri
        description: Source file URI/path used during ingestion (if available).

  - name: stg_order_items
    description: Staging model for order items with numeric casting and ingestion lineage.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - order_id
              - order_item_id
              - load_date

    columns:
      - name: order_id
        description: Identifier of the order this item belongs to.
        tests:
          - not_null

      - name: order_item_id
        description: Sequential item number within an order.
        tests:
          - not_null

      - name: product_id
        description: Product identifier.
        tests:
          - not_null

      - name: seller_id
        description: Seller identifier.
        tests:
          - not_null

      - name: shipping_limit_ts
        description: Latest timestamp for the seller to ship the item.
        tests:
          - not_null

      - name: shipping_limit_dt
        description: Shipping limit date derived from shipping_limit_ts.
        tests:
          - not_null

      - name: price
        description: Item price (currency value).
        tests:
          - not_null

      - name: freight_value
        description: Freight/shipping cost for the item.
        tests:
          - not_null

      - name: load_date
        description: Batch partition date used for ingestion lineage and idempotency.
        tests:
          - not_null

      - name: ingestion_ts
        description: Ingestion timestamp for lineage and debugging.
        tests:
          - not_null

      - name: source_file
        description: Source file name used during ingestion (if available).

      - name: source_uri
        description: Source file URI/path used during ingestion (if available).

  - name: stg_customers
    description: Staging model for customers with geographic attributes and ingestion lineage.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - customer_id
              - load_date

    columns:
      - name: customer_id
        description: Customer identifier (unique within each load_date batch).
        tests:
          - not_null

      - name: customer_unique_id
        description: Unique customer identifier representing the real person across multiple orders.
        tests:
          - not_null

      - name: customer_zip_code_prefix
        description: ZIP code prefix used for geographic analysis.
        tests:
          - not_null

      - name: customer_city
        description: Customer city.

      - name: customer_state
        description: Customer state (UF). Values are not validated at staging layer to preserve source data integrity.

      - name: load_date
        description: Batch partition date used for ingestion lineage and idempotency.
        tests:
          - not_null

      - name: ingestion_ts
        description: Ingestion timestamp for lineage and debugging.
        tests:
          - not_null

      - name: source_file
        description: Source file name used during ingestion (if available).

      - name: source_uri
        description: Source file URI/path used during ingestion (if available).

  - name: stg_products
    description: Staging model for products with basic normalization and ingestion lineage.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - product_id
              - load_date

    columns:
      - name: product_id
        description: Product identifier (unique within each load_date batch).
        tests:
          - not_null

      - name: product_category_name
        description: Normalized product category name (lowercase and trimmed).

      - name: product_name_length
        description: Character length of the product name (as provided by the source).

      - name: product_description_length
        description: Character length of the product description (as provided by the source).

      - name: product_photos_qty
        description: Number of product photos available.
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: product_weight_g
        description: Product weight in grams.
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: product_length_cm
        description: Product length in centimeters.
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: product_height_cm
        description: Product height in centimeters.
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: product_width_cm
        description: Product width in centimeters.
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

      - name: load_date
        description: Batch partition date used for ingestion lineage and idempotency.
        tests:
          - not_null

      - name: ingestion_ts
        description: Ingestion timestamp for lineage and debugging.
        tests:
          - not_null

      - name: source_file
        description: Source file name used during ingestion (if available).

      - name: source_uri
        description: Source file URI/path used during ingestion (if available).


  - name: stg_sellers
    description: Staging model for sellers with geographic attributes normalization and ingestion lineage.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - seller_id
              - load_date

    columns:
      - name: seller_id
        description: Seller identifier (unique within each load_date batch).
        tests:
          - not_null

      - name: seller_zip_code_prefix
        description: ZIP code prefix used for geographic analysis.

      - name: seller_city
        description: Seller city (lowercased, trimmed, empty strings converted to null).

      - name: seller_state
        description: Seller state (UF, uppercased, trimmed, empty strings converted to null).
        tests:
          - accepted_values:
              arguments:
                values:
                  - AC
                  - AL
                  - AP
                  - AM
                  - BA
                  - CE
                  - DF
                  - ES
                  - GO
                  - MA
                  - MT
                  - MS
                  - MG
                  - PA
                  - PB
                  - PR
                  - PE
                  - PI
                  - RJ
                  - RN
                  - RS
                  - RO
                  - RR
                  - SC
                  - SP
                  - SE
                  - TO
              config:
                severity: warn

      - name: load_date
        description: Batch partition date used for ingestion lineage and idempotency.
        tests:
          - not_null

      - name: ingestion_ts
        description: Ingestion timestamp for lineage and debugging.
        tests:
          - not_null

      - name: source_file
        description: Source file name used during ingestion (if available).

      - name: source_uri
        description: Source file URI/path used during ingestion (if available).